Other API's sample code
trimble-oss/Ag-Data-API-Examples pull request #23
Opened 2023-10-23 19:47 UTC by dabsun01

2023-10-23 21:56 UTC, haydencbarnes requested changes

2023-10-23 21:56 UTC, haydencbarnes commented on code_samples/CSharp_samples/SampleClientCode/FieldsClient.cs
> +            //change the field name every time you make a request as the filed api does not allow duplicate names
```suggestion
            //change the field name every time you make a request as the field api does not allow duplicate names
```

2023-10-23 21:56 UTC, haydencbarnes commented on code_samples/CSharp_samples/SampleClientCode/BoundariesClient.cs
> +                Name = "Some Test Boundary15",
Add: // Add your boundary info here

2023-10-23 21:56 UTC, haydencbarnes commented on code_samples/CSharp_samples/SampleClientCode/GuidanceLinesClient.cs
> +                Name = "Some Guidance Line15",
Add: // Add your guidance line info here

2023-10-23 22:06 UTC, dabsun01 commented on code_samples/CSharp_samples/SampleClientCode/FieldsClient.cs
> +            //change the field name every time you make a request as the filed api does not allow duplicate names
fixed

2023-10-23 22:07 UTC, dabsun01 commented on code_samples/CSharp_samples/SampleClientCode/BoundariesClient.cs
> +                Name = "Some Test Boundary15",
fixed

2023-10-23 22:07 UTC, dabsun01 commented on code_samples/CSharp_samples/SampleClientCode/GuidanceLinesClient.cs
> +                Name = "Some Guidance Line15",
fixed

2023-10-24 23:18 UTC, haydencbarnes approved these changes

2023-10-24 23:18 UTC, merged